#!/bin/bash
# Quick Setup Script for Spotify Music App Deployment

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Spotify Music App - Quick GitHub Deployment Guide         ║"
echo "║                   By Abhishek Upadhayay                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Create GitHub Repository${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: spotify-music-app"
echo "3. Description: Modern music streaming app with login and player"
echo "4. Select: PUBLIC"
echo "5. Skip 'Initialize with README' (we have one)"
echo "6. Click: Create repository"
echo ""
echo -e "${YELLOW}⏸ Wait for repository to be created, then continue...${NC}"
echo ""

echo -e "${BLUE}Step 2: Push Code to GitHub${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Copy and run these commands in your terminal:"
echo ""
echo -e "${GREEN}cd d:\\spotify${NC}"
echo -e "${GREEN}git remote add origin https://github.com/codewithabhi044/spotify-music-app.git${NC}"
echo -e "${GREEN}git branch -M main${NC}"
echo -e "${GREEN}git push -u origin main${NC}"
echo ""
echo "When prompted, enter your GitHub credentials (or use personal access token)"
echo ""

echo -e "${BLUE}Step 3: Enable GitHub Pages${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to: https://github.com/codewithabhi044/spotify-music-app"
echo "2. Click: Settings (top right)"
echo "3. Click: Pages (left sidebar)"
echo "4. Under 'Source', select: main branch, / (root)"
echo "5. Click: Save"
echo "6. Wait 30 seconds..."
echo ""
echo -e "${GREEN}✓ Your app will be live at:${NC}"
echo "  https://codewithabhi044.github.io/spotify-music-app/"
echo ""

echo -e "${BLUE}Step 4: (Optional) Deploy to Vercel${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "For faster performance, deploy to Vercel:"
echo "1. Go to: https://vercel.com/import"
echo "2. Click: Import Git Repository"
echo "3. Paste: https://github.com/codewithabhi044/spotify-music-app.git"
echo "4. Click: Import → Deploy"
echo ""
echo -e "${GREEN}✓ Your app will be live at:${NC}"
echo "  https://spotify-music-app.vercel.app/"
echo ""

echo -e "${BLUE}Step 5: Share Your App${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Copy this share text for social media:"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🎵 Check out my new Spotify Music App!"
echo ""
echo "A modern, responsive music streaming app with:"
echo "✨ Beautiful dark theme (Spotify-inspired)"
echo "🔐 Mobile number login with OTP"
echo "🎵 High-quality music player"
echo "📱 Works on all devices (mobile, tablet, desktop)"
echo "🌐 Shareable links"
echo ""
echo "Visit: [YOUR_URL_HERE]"
echo ""
echo "👤 Built by Abhishek Upadhayay"
echo "📞 Contact: +91 9878229978"
echo "🐙 GitHub: github.com/codewithabhi044"
echo "📸 Instagram: @ig.abhishek21"
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}✓ Setup Complete!${NC}"
echo ""
echo "What's Included:"
echo "  ✓ Modern responsive design"
echo "  ✓ Mobile number authentication"
echo "  ✓ Music player with controls"
echo "  ✓ About section with contact info"
echo "  ✓ Share functionality (WhatsApp, Facebook, Twitter)"
echo "  ✓ PWA support (installable app)"
echo "  ✓ Offline functionality"
echo "  ✓ Developer profile with all social links"
echo ""

echo "Need Help?"
echo "  📖 Read: DEPLOYMENT.md"
echo "  📖 Read: README.md"
echo "  📧 Email: abhishek@example.com (to be updated)"
echo "  📞 Call: +91 9878229978"
echo ""
